### PR TITLE
modified device tests to be compatible with RHMI 1.6

### PR DESCRIPTION
**Pull request by jhellar**
## Description

https://issues.redhat.com/browse/AGMS-1184

Test run: https://mobile-jenkins.rhev-ci-vms.eng.rdu2.redhat.com/job/jhellar-device/1/console

### CODE REVIEW

**Comment by b1zzu** [comment]
:eyes:

**Comment by b1zzu** [comment]
Sure we want to drop also the keycloak tests?

**Comment by jhellar** [comment]
I think so, AFAIK we won't be maintaining our own JS SDK for Keycloak anymore.

**Comment by b1zzu** [comment]
Yhe that's right

**Pull request merged**
